PassionProject/Models/Owner.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class Owner
    {
        //Ownerid
        [Key]
        public int OwnerId { get; set; }

        //First Name
        public string OwnerFistName { get; set; }

        //Last Name
        public string OwnerLastName { get; set; }

        //Pen Name
        public string OwnerPenName { get; set; }

        //Owner Number
        public string OwnerPhoneNo { get; set; }

        //EmailId
        public string OwnerEmailId { get; set; }

        //We can represent one author with many pets this 
        //is how we make one to many relationship
        public virtual ICollection<Pet> Pets { get; set; }

    }
}

PassionProject/Controllers/OwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using System.Net;
using System.Data.Entity;

namespace PassionProject.Controllers
{
    public class OwnerController : Controller
    {
        private PetCareContext db = new PetCareContext();
        // GET: Owner
        public ActionResult Create()
        {
            return View();
        }

        //POST: Create Owner
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OwnerId,OwnerFistName,OwnerLastName,OwnerPenName,OwnerPhoneNo,OwnerEmailId")] Owner owner)
        {
            if (ModelState.IsValid)
            {
                db.owner.Add(owner);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(owner);
        }
        //GET : List of Owners
        public ActionResult List()
        {
            return View(db.owner.ToList());
        }
        //GET: Details of particular Owner
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Owner owner = db.owner.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
            
        }
        //GET : Edit Owner Details
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Owner owner = db.owner.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OwnerId,OwnerFistName,OwnerLastName,OwnerPenName,OwnerPhoneNo,OwnerEmailId")] Owner owner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(owner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(owner);
        }
        //GET: Delete owner
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Owner owner = db.owner.Find(id);
            if (owner == null)
            {
                return HttpNotFound();
            }
            return View(owner);
        }
        //POST : delete owner
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Owner owner = db.owner.Find(id);
            db.owner.Remove(owner);
            db.SaveChanges();
            return RedirectToAction("List");
            //return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PassionProject/Views/Owner/Create.cshtml
@model PassionProject.Models.Owner
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts{
    <link href="~/admin-lte/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/admin-lte/css/AdminLTE.css" rel="stylesheet" />

}
@using (Html.BeginForm("Create", "Owner", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="login-box">
        <div class="login-logo">
            <a href="#"></a>
        </div>
        <div class="login-box-body">
            <p class="login-box-msg">
                <h3 class="CenterHeader">ADD OWNER DETAILS</h3>
            </p>
            @*<span class="glyphicon glyphicon-lock form-control-feedback"></span>*@
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.OwnerFistName, new { @class = "form-control", @placeholder = "First Name" })
            </div>
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.OwnerLastName, new { @class = "form-control", @placeholder = "Last Name" })
            </div>
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.OwnerPenName, new { @class = "form-control", @placeholder = "Pen Name" })
            </div>
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.OwnerPhoneNo, new { @class = "form-control", @placeholder = "Phone No" })
            </div>
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.OwnerEmailId, new { @class = "form-control", @placeholder = "EmailID" })
            </div>

            <div class="row">
                <input type="submit" name="submit" value="Submit" class="btn btn-primary col-md-12" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "List",
             new { controller = "Owner" },
             new { @class = "btn btn-primary" })
    </div>
}

PassionProject/Views/Owner/Delete.cshtml
@model PassionProject.Models.Owner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<form class="form-horizontal">
    <h4>Owner</h4>
    <hr />
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerFistName)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.OwnerFistName)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerLastName)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.OwnerLastName)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerPenName)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.OwnerPenName)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerPhoneNo)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.OwnerPhoneNo)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.OwnerEmailId)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.OwnerEmailId)
        </div>
    </div>
</form>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-primary" /> |
    @Html.ActionLink("Back to List", "List",
        new { controller = "Owner"},
        new { @class = "btn btn-primary"})

</div>
}

PassionProject/Views/Owner/Details.cshtml
@model PassionProject.Models.Owner

@{
    ViewBag.Title = "Details";
}

<div class="login-box">
    <div class="login-logo">
        <a href="#"></a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg">
            <h3 class="CenterHeader">View Owner Details</h3>
        </p>
        
        <div class="form-group has-feedback">
            @Html.Label("First Name")
            @Html.TextBoxFor(m => m.OwnerFistName, new { @class = "form-control", @placeholder = "First Name" , @readonly = "readonly" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Last Name")
            @Html.TextBoxFor(m => m.OwnerLastName, new { @class = "form-control", @placeholder = "Last Name", @readonly = "readonly" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Pen Name")
            @Html.TextBoxFor(m => m.OwnerPenName, new { @class = "form-control", @placeholder = "Pen Name", @readonly = "readonly" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Phone No")
            @Html.TextBoxFor(m => m.OwnerPhoneNo, new { @class = "form-control", @placeholder = "Phone No", @readonly = "readonly" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("EmailID")
            @Html.TextBoxFor(m => m.OwnerEmailId, new { @class = "form-control", @placeholder = "EmailID", @readonly = "readonly" })
        </div>
    </div>
</div>
<p>

    @Html.ActionLink("Edit", "Edit", new { id = Model.OwnerId }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "List",
         new { controller = "Owner" },
         new { @class = "btn btn-primary" })
</p>

PassionProject/Views/Owner/Edit.cshtml
@model PassionProject.Models.Owner

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="login-box">
    <div class="login-logo">
        <a href="#"></a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg">
            <h3 class="CenterHeader">Edit Owner Details</h3>
        </p>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OwnerId)

        <div class="form-group has-feedback">
            @Html.Label("First Name")
            @Html.TextBoxFor(m => m.OwnerFistName, new { @class = "form-control", @placeholder = "First Name" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Last Name")
            @Html.TextBoxFor(m => m.OwnerLastName, new { @class = "form-control", @placeholder = "Last Name" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Pen Name")
            @Html.TextBoxFor(m => m.OwnerPenName, new { @class = "form-control", @placeholder = "Pen Name" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Phone No")
            @Html.TextBoxFor(m => m.OwnerPhoneNo, new { @class = "form-control", @placeholder = "Phone No" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("EmailID")
            @Html.TextBoxFor(m => m.OwnerEmailId, new { @class = "form-control", @placeholder = "EmailID" })
        </div>

        <div class="row">
            <input type="submit" name="submit" value="Submit" class="btn btn-primary col-md-12" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "List",
                 new { controller = "Owner" },
                 new { @class = "btn btn-primary" })
</div>

PassionProject/Views/Owner/List.cshtml
@model IEnumerable<PassionProject.Models.Owner>

@{
    ViewBag.Title = "List";
}

<h2>Owner List</h2>

<p>
    @Html.ActionLink("Create New", "Create",
             new { controller = "Owner" },
             new { @class = "btn btn-primary" })
</p>
<div class="table table-responsive">
    <table class="table table-hover">
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.OwnerFistName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerLastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerPenName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerPhoneNo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OwnerEmailId)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="active">
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerFistName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerLastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerPenName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerPhoneNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OwnerEmailId)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.OwnerId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.OwnerId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.OwnerId })
                </td>
            </tr>
        }

    </table>
</div>