PassionProject/Models/CareTaker.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class CareTaker
    {
        //Caretakerid
        [Key]
        public int CaretakerId { get; set; }

        //Caretaker First Name
        public string CaretakerFirstName { get; set; }

        //Caretaker Last Name
        public string CaretakerLastName { get; set; }

        //pet id
        public virtual Pet pet { get; set; }
    }
}

PassionProject/Controllers/CareTakerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Data.Entity;
using PassionProject.Models;

namespace PassionProject.Controllers
{
    public class CareTakerController : Controller
    {
        private PetCareContext db = new PetCareContext();
        // GET: CareTaker
        public ActionResult Create()
        {
            return View();
        }
        //POST : Save caretaker Data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CaretakerId,CaretakerFirstName,CaretakerLastName")] CareTaker caretaker)
        {
            if (ModelState.IsValid)
            {
                db.caretaker.Add(caretaker);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(caretaker);
        }
        //GET:  List of caretaker
        public ActionResult List()
        {
            return View(db.caretaker.ToList());
        }
        //GET: Details of particular Owner
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CareTaker caretaker = db.caretaker.Find(id);
            if (caretaker == null)
            {
                return HttpNotFound();
            }
            return View(caretaker);

        }
        //GET : Edit Owner Details
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CareTaker caretaker = db.caretaker.Find(id);
            if (caretaker == null)
            {
                return HttpNotFound();
            }
            return View(caretaker);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CaretakerId,CaretakerFirstName,CaretakerLastName")] CareTaker caretaker)
        {
            if (ModelState.IsValid)
            {
                db.Entry(caretaker).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(caretaker);
        }
        //GET: Delete owner
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CareTaker caretaker = db.caretaker.Find(id);
            if (caretaker == null)
            {
                return HttpNotFound();
            }
            return View(caretaker);
        }
        //POST : delete owner
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            CareTaker caretaker = db.caretaker.Find(id);
            db.caretaker.Remove(caretaker);
            db.SaveChanges();
            return RedirectToAction("List");
            //return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PassionProject/Views/CareTaker/Create.cshtml
@model PassionProject.Models.CareTaker
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <link href="~/admin-lte/css/AdminLTE.min.css" rel="stylesheet" />
    <link href="~/admin-lte/css/AdminLTE.css" rel="stylesheet" />

}
@using (Html.BeginForm("Create", "CareTaker", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="login-box">
        <div class="login-logo">
            <a href="#"></a>
        </div>
        <div class="login-box-body">
            <p class="login-box-msg">
                <h3 class="CenterHeader">ADD OWNER DETAILS</h3>
            </p>
            @*<span class="glyphicon glyphicon-lock form-control-feedback"></span>*@
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.CaretakerFirstName, new { @class = "form-control", @placeholder = "First Name" })
            </div>
            <div class="form-group has-feedback">
                @Html.TextBoxFor(m => m.CaretakerLastName, new { @class = "form-control", @placeholder = "Last Name" })
            </div>
            <div class="row">
                <input type="submit" name="submit" value="Submit" class="btn btn-primary col-md-12" />
            </div>
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "List",
             new { controller = "CareTaker" },
             new { @class = "btn btn-primary" })
    </div>
}

PassionProject/Views/CareTaker/Delete.cshtml
@model PassionProject.Models.CareTaker

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<form class="form-horizontal">
    <h4>CareTaker</h4>
    <hr />
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.CaretakerFirstName)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.CaretakerFirstName)
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2">
            @Html.DisplayNameFor(model => model.CaretakerLastName)
        </div>
        <div class="col-sm-2">
            @Html.DisplayFor(model => model.CaretakerLastName)
        </div>
    </div>
</form>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-primary" /> |
    @Html.ActionLink("Back to List", "List",
new { controller = "CareTaker"},
new { @class = "btn btn-primary"})

</div>
}

PassionProject/Views/CareTaker/Details.cshtml
@model PassionProject.Models.CareTaker

@{
    ViewBag.Title = "Details";
}
<div class="login-box">
    <div class="login-logo">
        <a href="#"></a>
    </div>
    <div class="login-box-body">
        <p class="login-box-msg">
            <h3 class="CenterHeader">View CareTaker Details</h3>
        </p>
        
        <div class="form-group has-feedback">
            @Html.Label("First Name")
            @Html.TextBoxFor(m => m.CaretakerFirstName, new { @class = "form-control", @placeholder = "First Name", @readonly = "readonly" })
        </div>
        <div class="form-group has-feedback">
            @Html.Label("Last Name")
            @Html.TextBoxFor(m => m.CaretakerLastName, new { @class = "form-control", @placeholder = "Last Name", @readonly = "readonly" })
        </div>
    </div>
</div>
<p>

    @Html.ActionLink("Edit", "Edit", new { id = Model.CaretakerId }, new { @class = "btn btn-primary"} ) |
    @Html.ActionLink("Back to List", "List",
         new { controller = "CareTaker" },
         new { @class = "btn btn-primary" })

</p>

PassionProject/Views/CareTaker/Edit.cshtml
@model PassionProject.Models.CareTaker

@{
    ViewBag.Title = "Edit";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="login-box">
        <div class="login-logo">
            <a href="#"></a>
        </div>
        <div class="login-box-body">
            <p class="login-box-msg">
                <h3 class="CenterHeader">Edit CareTaker Details</h3>
            </p>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.CaretakerId)

            <div class="form-group has-feedback">
                @Html.Label("First Name")
                @Html.TextBoxFor(m => m.CaretakerFirstName, new { @class = "form-control", @placeholder = "First Name" })
            </div>
            <div class="form-group has-feedback">
                @Html.Label("Last Name")
                @Html.TextBoxFor(m => m.CaretakerLastName, new { @class = "form-control", @placeholder = "Last Name" })
            </div>

            <div class="row">
                <input type="submit" name="submit" value="Submit" class="btn btn-primary col-md-12" />
            </div>
        </div>
    </div>

}

    <div>
        @Html.ActionLink("Back to List", "List",
                 new { controller = "CareTaker" },
                 new { @class = "btn btn-primary" })
    </div>

PassionProject/Views/CareTaker/List.cshtml
@model IEnumerable<PassionProject.Models.CareTaker>

@{
    ViewBag.Title = "List";
}

<h2>Caretaker List</h2>

<p>
    @Html.ActionLink("Create New", "Create",
             new { controller = "CareTaker" },
             new { @class = "btn btn-primary" })
</p>
<div class="table table-responsive">
    <table class="table table-hover">
        <tr class="success">
            <th>
                @Html.DisplayNameFor(model => model.CaretakerFirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CaretakerLastName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr class="active">
                <td>
                    @Html.DisplayFor(modelItem => item.CaretakerFirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CaretakerLastName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.CaretakerId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.CaretakerId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.CaretakerId })
                </td>
            </tr>
        }

    </table>
</div>